@startuml Deployment_diagram

node "PLC" {
  
}

node "Port Mirroring Switch" as PM

node "Profinet Device" as PD

node "Analyser" {
    component "Profinet Sniffer" as PS
    component "Data Handler" as DH
    component "GSDML Parser" as GP
    component "User Interface" as UI
    database "Device Data Storage" as DDS
    database "Historical IO Data" as HID
}

node "IO-Link Master" as IOlink {
  component "IO-Link Master" as IOM
}
node "IO-Link Device" as Device{
}
' Connections
PLC -- PM : Profinet\nCyclische data
PM --"0..*\n\n" IOM : Profinet\nCyclische data
PM --> PS : (Mirrored)Profinet\nCyclische data
IOM --"1..8" Device : IO-Link
PD- PM : Profinet\nCyclische data

DH -(0 HID
HID -0)- UI
DDS -(0 UI
GP -(0 DDS
PS -(0 DH : Queue
PS -0)- GP : Queue
@enduml