@startuml main_UCD
left to right direction

skinparam linetype polyline

actor Productiemanager as a1
actor "Technische dienst" as a2
actor Installateur as a4
actor Analyseplatform as a5

rectangle " " as rect{
rectangle "Configuratietoegang" as rect1{
usecase "Aanmaken sensoren" as uc1
usecase "Verwijderen sensoren" as uc2
usecase "Aanpassen sensoren" as uc3
usecase "Inzien sensoren" as uc4
}
rectangle "Informatietoegang" as rect2{
usecase "Inzien meetwaarden-realtime" as uc5
usecase "Inzien meetwaarden-historie" as uc6
usecase "Inzien analyse-waarschuwingen" as uc7
}
usecase "Instellen analyseplatform" as uc8
usecase "Aanleveren analyse-waarschuwingen" as uc9
}

a1 --- rect2

a2 --- rect1

a4 --- rect1

a4 -- uc8

a2 --- rect2

uc7 --> uc9 : <<include>>

uc9 - a5

uc6 -- a5

uc8 -- a5

@enduml
